UUID:
  playerUUID:
REPORT_TYPE:
  BHOP:
    MATERIAL: 'IRON_BOOTS'
  NUKER:
    MATERIAL: 'TNT'
  AIMBOT:
    MATERIAL: 'BOW'
  FLYING:
    MATERIAL: 'FEATHER'
  KILLAURA:
    MATERIAL: 'BLAZE_POWDER'
  VELOCITY:
    MATERIAL: 'ANVIL'
  AUTOCLICKING:
    MATERIAL: 'IRON_SWORD'