main: me.xaxis.reportplus.ReportPlus
name: ReportPlus
description: Report plugin
author: Xaxis
version: 0
api-version: 1.19
commands:
  report:
    description: Report a player
  reports:
    description: admin command.
